
title: The Graduate Researcher's Field Guide
description: Survival protocols for IP protection and professional agency in academia.
theme: jekyll-theme-minimal
logo: /assets/social-preview.png
show_downloads: false
plugins:
  - jekyll-seo-tag

url: "https://alanmdaniel.github.io"
baseurl: "/Researcher-Professional-Development"
permalink: pretty
